version: "3.9"

services:
  db:
    image: postgres:13.4
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=participons_docker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=japon+72-2
  backend:
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  # frontend:
  #   restart: always
  #   build:
  #     context: frontend
  #     dockerfile: Dockerfile
  #   command: npm run build
  #   volumes:
  #     - ./frontend:/code
  #     - /code/node_modules
  #     - /code/.nuxt
  #   ports:
  #     - "3000:3000"
