version: "3.9"

services:
  app:
    build:
      context: app
    # restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/api/staticfiles
      - media_volume:/home/app/api/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: nginx
    # restart: always
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/api/staticfiles
      - media_volume:/home/app/api/mediafiles

  frontend:
    build: frontend
    volumes:
      - ./:/home/app/web
    working_dir: /home/app/web
    # env_file:
    #   - .env
    command: bash -c "npm i && npm run build"

volumes:
  postgres_data:
  static_volume:
  media_volume:
