# Generated by Django 3.2.5 on 2021-08-18 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='id',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='id_user_answer',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.TextField(max_length=1000),
        ),
    ]
