# Generated by Django 3.2.5 on 2021-09-01 10:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0008_remove_project_is_over'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='id_user_answer',
            new_name='id_owner_answer',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('owner', 'question')},
        ),
    ]
