# Generated by Django 3.2.7 on 2021-09-13 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20210901_1241'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projecttype',
            unique_together={('id_project_type', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='questiontype',
            unique_together={('id_question_type', 'name')},
        ),
    ]
