# Generated by Django 3.2.5 on 2021-07-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='creator',
            new_name='owner',
        ),
    ]
