# Generated by Django 3.2.5 on 2021-07-15 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='creator_email',
            new_name='creator',
        ),
    ]
