# Generated by Django 3.2.5 on 2021-08-18 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0005_auto_20210818_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('owner', 'project')},
        ),
    ]
