# Generated by Django 3.2.5 on 2021-07-08 14:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='address',
            name='unique_address_owner',
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('owner_id',)},
        ),
    ]
