# Generated by Django 3.2.5 on 2021-08-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='num',
            field=models.IntegerField(),
        ),
    ]
