---
name: Continuous Deployment

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: sh -c "python ../app.manage.py test tests"

  # lint:
  #   name: Lint
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Lint
  #       run: docker-compose run --rm app sh -c "flake8 --max-line-length=120"
